### ISSUE TITLE
add support for a progress bar

### ISSUE THREAD

**Issue by Emungui** [monperrus/ExpandAnimations#19]
I succesfully installed the 0.4 version. However when I export the odp file to PDF the effects are not displayed

**Comment by quendil** [comment]
@Emungui I just tested it in LibreOffice 5.4 and it worked perfectly. You might have misused it : have you done "Tools/Add-Ons/Expand animations" before exporting to PDF ?

**Comment by pdinklag** [comment]
I was just about to second the issue, but it **did** work, it's just not easy to realize.

The extension seems to open a new document (`*-expanded`) and then it takes quite a long while (for a long presentation) to finish. However, there is no indication that anything is happening, and I tripped in the same trap twice by exporting to PDF, wondering why nothing happened, or closing LibreOffice while the extension was working. So the solution to this issue is just patience.

A progress bar, or any indication that something's happening for that matter, would be nice!

**Comment by monperrus** [comment]
You're right see https://github.com/monperrus/ExpandAnimations/issues/21

Contributions welcome!

**Comment by monperrus** [comment]
Does the progress bar of #27 work as expected? WDYT?

**Comment by monperrus** [comment]
Closed per #27

See new packaged file at https://github.com/monperrus/ExpandAnimations/blob/master/dist/ExpandAnimations-0.5.oxt
