### ISSUE TITLE
Does not install on LOo 7.3.1.3

### ISSUE THREAD

**Issue by liar666** [monperrus/ExpandAnimations#56]
Getting an error when opening the `.oxt` file (tried both .13 & .12 releases)

Sorry, LOo dialogs do not allow copying text, and I'm too lazy to copy the whole text, so I'm sending a screenshot of the error
![screenshot_2022-04-02-14 33](https://user-images.githubusercontent.com/3216927/161383671-5dff8eba-ac2f-499d-aa75-289102122803.png)

**Comment by GMTSE** [comment]
Responding to myself:

I managed to solve the problem by:
- manually creating the directory
- copying the `.oxt` file inside it
- forcing re-installation of the extension (opening the `.oxt` file in LOo, then saying 'yes' to "this extension is already instaleld, do you want to reinstall?")

I think the problem comes from the fact I had the extension installed a long time ago on a previous LOo version (ubuntu's default: 6?), then I reinstalled my machine and got a fresh new LOo version (latest from PPA: 7.3). Probably some files were referring to the old installation directory while other did not know about it due to the fresh installation... Might be a bug in LOo...

**Comment by PeterNerlich** [comment]
Worked flawlessly for me. Downloaded extension from here to /tmp/ and selected from there. LO is from the arch repos.

Version: 7.3.1.3 / LibreOffice Community
Build ID: 30(Build:3)
CPU threads: 4; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: en-GB (en_GB.UTF-8); UI: en-US
7.3.1-1
Calc: threaded
